# Objective: Run standard ELBO with parameters given in VV for UCI to match ~ their test log-likelihood

- name: match_vv
  experiment_name: uci_superconduct
  # hparams
  batch_size: 256
  hidden_dim: 50
  learning_rate: 0.001
  beta_elbo: 0.5
  beta_ood: 0
  prior_α: 1.0
  prior_β: 0.001
  seed: 2
  # data
  train_val_split: 0.99
  test_split: 0.1
  # pl trainer
  n_trials: 20
  max_epochs: -1
  early_stopping_patience: 50
  log_every_n_steps: 500 # How often to log within steps (defaults to every 50 steps)
  flush_logs_every_n_steps: 50 # How often does the log writes to disc
  progress_bar_refresh_rate: 0 # How often to refresh progress bar (in steps).
  check_val_every_n_epoch: 1 # Check val every n train epochs

- name: match_vv
  experiment_name: uci_yacht
  # hparams
  batch_size: 256
  hidden_dim: 50
  learning_rate: 0.001
  beta_elbo: 0.5
  beta_ood: 0
  prior_α: 1.
  prior_β: 0.001
  seed: 2
  # data
  train_val_split: 0.99
  test_split: 0.1
  # pl trainer
  n_trials: 20
  max_epochs: -1
  early_stopping_patience: 50
  log_every_n_steps: 500 # How often to log within steps (defaults to every 50 steps)
  flush_logs_every_n_steps: 50 # How often does the log writes to disc
  progress_bar_refresh_rate: 0 # How often to refresh progress bar (in steps).
  check_val_every_n_epoch: 1 # Check val every n train epochs