- name: mean_shift_05
  experiment_name: toy_shifted
  # hparams
  batch_size: 1024
  hidden_dim: 50
  beta_elbo: 0.5
  tau_ood: 0.5
  prior_α: 1.025
  prior_β: 0.5
  ood_x_generation_method: mean_shift
  ms_bw_factor: 0.5
  ms_kde_bw_factor: 1.3
  seed: 2
  shifting_proportion_total: 0.5
  shifting_proportion_k: 0.003
  # pl trainer
  early_stopping_patience: 250
  n_trials: 20
  max_epochs: -1
  log_every_n_steps: 500 # How often to log within steps (defaults to every 50 steps)
  flush_logs_every_n_steps: 50 # How often does the log writes to disc
  progress_bar_refresh_rate: 0 # How often to refresh progress bar (in steps).
  check_val_every_n_epoch: 1 # Check val every n train epochs

- name: mean_shift_05
  experiment_name: uci_ccpp_shifted
  # hparams
  batch_size: 1024
  hidden_dim: 50
  beta_elbo: 0.5
  tau_ood: 0.5
  prior_α: 1.5
  prior_β: 0.5
  ood_x_generation_method: mean_shift
  ms_bw_factor: 0.5
  ms_kde_bw_factor: 1.3
  split_training: True
  split_training_mode: split_training_std_vv_mean
  seed: 2
  shifting_proportion_total: 0.3
  shifting_proportion_k: 0.0002
  # pl trainer
  n_trials: 20
  max_epochs: -1
  log_every_n_steps: 500 # How often to log within steps (defaults to every 50 steps)
  flush_logs_every_n_steps: 50 # How often does the log writes to disc
  progress_bar_refresh_rate: 0 # How often to refresh progress bar (in steps).
  check_val_every_n_epoch: 1 # Check val every n train epochs

- name: mean_shift_05
  experiment_name: uci_concrete_shifted
  # hparams
  batch_size: 1024
  hidden_dim: 50
  beta_elbo: 0.5
  tau_ood: 0.5
  prior_α: 1.5
  prior_β: 0.5
  ood_x_generation_method: mean_shift
  ms_bw_factor: 0.5
  ms_kde_bw_factor: 1.3
  split_training: True
  split_training_mode: split_training_std_vv_mean
  seed: 2
  shifting_proportion_total: 0.7
  shifting_proportion_k: 0.001
  # pl trainer
  n_trials: 20
  max_epochs: -1
  log_every_n_steps: 500 # How often to log within steps (defaults to every 50 steps)
  flush_logs_every_n_steps: 50 # How often does the log writes to disc
  progress_bar_refresh_rate: 0 # How often to refresh progress bar (in steps).
  check_val_every_n_epoch: 1 # Check val every n train epochs

- name: mean_shift_05
  experiment_name: uci_superconduct_shifted
  # hparams
  batch_size: 1024
  hidden_dim: 50
  beta_elbo: 0.5
  tau_ood: 0.5
  prior_α: 1.5
  prior_β: 0.5
  ood_x_generation_method: mean_shift
  ms_bw_factor: 0.5
  ms_kde_bw_factor: 1.3
  split_training: True
  split_training_mode: split_training_std_vv_mean
  seed: 2
  shifting_proportion_total: 0.01
  shifting_proportion_k: 0.00005
  # pl trainer
  n_trials: 20
  max_epochs: -1
  log_every_n_steps: 500 # How often to log within steps (defaults to every 50 steps)
  flush_logs_every_n_steps: 50 # How often does the log writes to disc
  progress_bar_refresh_rate: 0 # How often to refresh progress bar (in steps).
  check_val_every_n_epoch: 1 # Check val every n train epochs

- name: mean_shift_05
  experiment_name: uci_wine_red_shifted
  # hparams
  batch_size: 1024
  hidden_dim: 50
  beta_elbo: 0.5
  tau_ood: 0.5
  prior_α: 1.5
  prior_β: 0.5
  ood_x_generation_method: mean_shift
  ms_bw_factor: 0.5
  ms_kde_bw_factor: 1.3
  split_training: True
  split_training_mode: split_training_std_vv_mean
  seed: 2
  shifting_proportion_total: 0.002
  shifting_proportion_k: 0.001
  # pl trainer
  n_trials: 20
  max_epochs: -1
  log_every_n_steps: 500 # How often to log within steps (defaults to every 50 steps)
  flush_logs_every_n_steps: 50 # How often does the log writes to disc
  progress_bar_refresh_rate: 0 # How often to refresh progress bar (in steps).
  check_val_every_n_epoch: 1 # Check val every n train epochs

- name: mean_shift_05
  experiment_name: uci_wine_white_shifted
  # hparams
  batch_size: 1024
  hidden_dim: 50
  beta_elbo: 0.5
  tau_ood: 0.5
  prior_α: 1.5
  prior_β: 0.5
  ood_x_generation_method: mean_shift
  ms_bw_factor: 0.5
  ms_kde_bw_factor: 1.3
  split_training: True
  split_training_mode: split_training_std_vv_mean
  seed: 2
  shifting_proportion_total: 0.0001
  shifting_proportion_k: 0.0004
  # pl trainer
  n_trials: 20
  max_epochs: -1
  log_every_n_steps: 500 # How often to log within steps (defaults to every 50 steps)
  flush_logs_every_n_steps: 50 # How often does the log writes to disc
  progress_bar_refresh_rate: 0 # How often to refresh progress bar (in steps).
  check_val_every_n_epoch: 1 # Check val every n train epochs


- name: mean_shift_05
  experiment_name: uci_yacht_shifted
  # hparams
  batch_size: 1024
  hidden_dim: 50
  beta_elbo: 0.5
  tau_ood: 0.5
  prior_α: 1.5
  prior_β: 0.5
  ood_x_generation_method: mean_shift
  ms_bw_factor: 0.5
  ms_kde_bw_factor: 1.3
  split_training: True
  split_training_mode: split_training_std_vv_mean
  seed: 2
  shifting_proportion_total: 0.95
  shifting_proportion_k: 0.006
  # pl trainer
  n_trials: 20
  max_epochs: -1
  log_every_n_steps: 500 # How often to log within steps (defaults to every 50 steps)
  flush_logs_every_n_steps: 50 # How often does the log writes to disc
  progress_bar_refresh_rate: 0 # How often to refresh progress bar (in steps).
  check_val_every_n_epoch: 1 # Check val every n train epochs