- name: gaussian_vae
  experiment_name: mnist_2d
  digits:
    - 2
    - 5
  model_name: vanilla_vae
  n_workers: 0
  # hparams
  batch_size: 500
  learning_rate: 1e-3
  eps: 1e-3
  # misc
  n_mc_samples: 1
  n_trials: 1
  seed: 3
  max_epochs: 30
  # pl trainer
  early_stopping_patience: 50
  log_every_n_steps: 10 # How often to log within steps (defaults to every 50 steps)
  flush_logs_every_n_steps: 50 # How often does the log writes to disc
  progress_bar_refresh_rate: 3 # How often to refresh progress bar (in steps).
  check_val_every_n_epoch: 1 # Check val every n train epochs

- name: standard_vv
  experiment_name: mnist_2d
  digits:
    - 2
    - 5
  model_name: v3ae
  n_workers: 0
  # hparams
  batch_size: 500
  learning_rate: 1e-3
  eps: 1e-3
  # From prior_gamma_per_pixel - for MNIST only
  prior_α: 0.3927581767454884 # 1.625
  prior_β: 0.0010704155012337458
  # ood
  # tau_ood: 0.5
  # ood_z_generation_method: kde
  # kde_bandwidth_multiplier: 27
  # misc
  n_mc_samples: 1
  n_trials: 1
  seed: 3
  max_epochs: 30
  # pl trainer
  early_stopping_patience: 50
  log_every_n_steps: 10 # How often to log within steps (defaults to every 50 steps)
  flush_logs_every_n_steps: 50 # How often does the log writes to disc
  progress_bar_refresh_rate: 3 # How often to refresh progress bar (in steps).
  check_val_every_n_epoch: 1 # Check val every n train epochs

- name: robust_vv
  experiment_name: mnist_2d
  digits:
    - 2
    - 5
  model_name: v3ae
  n_workers: 0
  # hparams
  batch_size: 500
  learning_rate: 1e-3
  eps: 1e-3
  # From prior_gamma_per_pixel - for MNIST only
  prior_α:  0.3927581767454884 # 1.625
  prior_β: 0.0010704155012337458
  # ood
  tau_ood: 0.5
  ood_z_generation_method: kde
  kde_bandwidth_multiplier: 9
  # misc
  n_mc_samples: 5
  n_trials: 1
  seed: 3
  max_epochs: 30
  # pl trainer
  early_stopping_patience: 50
  log_every_n_steps: 50 # How often to log within steps (defaults to every 50 steps)
  flush_logs_every_n_steps: 50 # How often does the log writes to disc
  progress_bar_refresh_rate: 3 # How often to refresh progress bar (in steps).
  check_val_every_n_epoch: 1 # Check val every n train epochs
