# - name: f_v3ae_samples
#   experiment_name: fashion_mnist
#   model_name: v3ae
#   n_workers: 0
#   # hparams
#   batch_size: 128
#   learning_rate: 1e-3
#   eps: 1e-3
#   latent_dims:
#     - 10
#   # ood
#   tau_ood: 0.
#   # prior
#   prior_α: 2.
#   prior_β: 0.001
#   # misc
#   n_trials: 10
#   seed: 3
#   max_epochs: 100
#   # pl trainer
#   early_stopping_patience: 200
#   log_every_n_steps: 10 # How often to log within steps (defaults to every 50 steps)
#   flush_logs_every_n_steps: 10 # How often does the log writes to disc
#   progress_bar_refresh_rate: 3 # How often to refresh progress bar (in steps).
#   check_val_every_n_epoch: 3 # Check val every n train epochs

# - name: f_v3ae_samples_pi
#   experiment_name: fashion_mnist
#   model_name: v3ae
#   n_workers: 0
#   # hparams
#   batch_size: 128
#   learning_rate: 1e-3
#   eps: 1e-3
#   latent_dims:
#     - 10
#   # prior
#   prior_α: 2.
#   prior_β: 0.001
#   # ood
#   tau_ood: 0.5
#   ood_z_generation_method: gd_aggregate_posterior
#   # misc
#   n_trials: 10
#   seed: 3
#   max_epochs: 100
#   # pl trainer
#   early_stopping_patience: 200
#   log_every_n_steps: 10 # How often to log within steps (defaults to every 50 steps)
#   flush_logs_every_n_steps: 10 # How often does the log writes to disc
#   progress_bar_refresh_rate: 3 # How often to refresh progress bar (in steps).
#   check_val_every_n_epoch: 3 # Check val every n train epochs

# - name: f_v3ae_for_er
#   experiment_name: fashion_mnist
#   model_name: v3ae
#   n_workers: 0
#   # hparams
#   batch_size: 128
#   learning_rate: 1e-3
#   eps: 1e-4
#   n_mc_samples: 3
#   decoder_α_offset: 1e-4
#   latent_dims:
#     - 2
#   # ood
#   tau_ood: 0.5
#   ood_z_generation_method: gd_aggregate_posterior
#   # prior
#   prior_α: 11.0
#   prior_β: 1e-3
#   prior_extrapolation_x: 1e4
#   prior_extrapolation_mode: on_centroids
#   # misc
#   n_trials: 10
#   seed: 3
#   max_epochs: 100
#   # pl trainer
#   early_stopping_patience: 200
#   log_every_n_steps: 10 # How often to log within steps (defaults to every 50 steps)
#   flush_logs_every_n_steps: 10 # How often does the log writes to disc
#   progress_bar_refresh_rate: 3 # How often to refresh progress bar (in steps).
#   check_val_every_n_epoch: 5 # Check val every n train epochs

# - name: f_v3ae_grid_reconstruct
#   experiment_name: mnist
#   model_name: v3ae
#   n_workers: 0
#   # hparams
#   batch_size: 128
#   learning_rate: 1e-3
#   eps: 1e-4
#   n_mc_samples: 3
#   decoder_α_offset: 1e-4
#   latent_dims:
#     - 2
#   # ood
#   tau_ood: 0.5
#   ood_z_generation_method: gd_aggregate_posterior
#   # prior
#   prior_α: 11.0
#   prior_β: 1e-3
#   prior_extrapolation_x: 1e4
#   prior_extrapolation_mode: on_centroids
#   # misc
#   n_trials: 10
#   seed: 3
#   max_epochs: 100
#   # pl trainer
#   early_stopping_patience: 200
#   log_every_n_steps: 10 # How often to log within steps (defaults to every 50 steps)
#   flush_logs_every_n_steps: 10 # How often does the log writes to disc
#   progress_bar_refresh_rate: 3 # How often to refresh progress bar (in steps).
#   check_val_every_n_epoch: 5 # Check val every n train epochs

- name: f_v3ae_samples_likelihood
  experiment_name: fashion_mnist
  model_name: v3ae
  n_workers: 0
  # hparams
  batch_size: 128
  learning_rate: 1e-3
  eps: 1e-7
  n_mc_samples: 3
  decoder_α_offset: 1e-4
  latent_dims:
    - 10
  # ood
  # prior
  tau_ood: 0.5
  ood_z_generation_method: gd_aggregate_posterior
  # prior
  prior_α: 2
  prior_β: 1e-6
  # misc
  n_trials: 10
  seed: 3
  max_epochs: 100
  # pl trainer
  early_stopping_patience: 200
  log_every_n_steps: 100 # How often to log within steps (defaults to every 50 steps)
  flush_logs_every_n_steps: 100 # How often does the log writes to disc
  progress_bar_refresh_rate: 3 # How often to refresh progress bar (in steps).
  check_val_every_n_epoch: 10 # Check val every n train epochs