- name: benchmark_gaussian_noise
  experiment_name: toy
  # hparams
  batch_size: 1024
  hidden_dim: 50
  beta_elbo: 1
  beta_ood: 1
  prior_alpha: 1.025
  prior_beta: 0.5
  ood_x_generation_method: gaussian_noise
  # pl trainer
  n_trials: 5
  max_epochs: -1
  log_every_n_steps: 500 # How often to log within steps (defaults to every 50 steps)
  flush_logs_every_n_steps: 50 # How often does the log writes to disc
  progress_bar_refresh_rate: 0 # How often to refresh progress bar (in steps).
  check_val_every_n_epoch: 1 # Check val every n train epochs

# - name: investigate_nan
#   experiment_name: uci_ccpp
#   # hparams
#   batch_size: 1024
#   hidden_dim: 50
#   beta_elbo: 1
#   beta_ood: 1
#   prior_alpha: 1.05
#   prior_beta: 0.5
#   ood_x_generation_method: optimised_x_ood_v_optimised
#   # pl trainer
#   n_trials: 10
#   max_epochs: 10
#   # TODO opt
#   automatic_optimization: False
#   log_every_n_steps: 1 # How often to log within steps (defaults to every 50 steps)
#   flush_logs_every_n_steps: 1 # How often does the log writes to disc
#   progress_bar_refresh_rate: 0 # How often to refresh progress bar (in steps).
#   check_val_every_n_epoch: 1 # Check val every n train epochs
