- name: test_new_formulation
  experiment_name: toy
  # hparams
  batch_size: 1024
  hidden_dim: 50
  beta_elbo: 1
  beta_ood: 1
  ood_x_generation_method: gaussian_noise_around_x # optimised_x_ood_v_optimised
  early_stopping_patience: 500
  # prior_alpha: 1.5
  # prior_beta: 10
  # pl trainer
  n_trials: 2
  max_epochs: -1
  log_every_n_steps: 500 # How often to log within steps (defaults to every 50 steps)
  flush_logs_every_n_steps: 50 # How often does the log writes to disc
  progress_bar_refresh_rate: 0 # How often to refresh progress bar (in steps).
  # val_check_interval: 5 # How often to check the validation set.
  check_val_every_n_epoch: 1 # Check val every n train epochs

# - name: test_benchmark_v_optimised
#   experiment_name: uci_ccpp
#   # hparams
#   batch_size: 1024
#   hidden_dim: 50
#   beta_elbo: 1
#   beta_ood: 1
#   prior_alpha: 1.05
#   prior_beta: 0.5
#   ood_x_generation_method: gaussian_noise_around_x
#   # pl trainer
#   n_trials: 3
#   max_epochs: 1000
#   # automatic_optimization: False
#   # gradient_clip_val: 1
#   log_every_n_steps: 50 # How often to log within steps (defaults to every 50 steps)
#   flush_logs_every_n_steps: 100 # How often does the log writes to disc
#   progress_bar_refresh_rate: 0 # How often to refresh progress bar (in steps).
#   check_val_every_n_epoch: 1 # Check val every n train epochs
