- name: v3ae_samples_likelihood_a2_5_b4e-2
  experiment_name: cifar
  model_name: v3ae
  n_workers: 0
  # hparams
  batch_size: 128
  learning_rate: 1e-3
  eps: 1e-3
  n_mc_samples: 1
  decoder_α_offset: 1e-3
  # ood
  # prior
  tau_ood: 0
  # prior
  prior_α: 2.5
  prior_β: 4e-2
  # misc
  n_trials: 1
  seed: 3
  max_epochs: 200
  # pl trainer
  early_stopping_patience: 200
  log_every_n_steps: 100 # How often to log within steps (defaults to every 50 steps)
  flush_logs_every_n_steps: 100 # How often does the log writes to disc
  progress_bar_refresh_rate: 3 # How often to refresh progress bar (in steps).
  check_val_every_n_epoch: 10 # Check val every n train epochs

- name: v3ae_samples_likelihood_a2_7_b3e-2
  experiment_name: cifar
  model_name: v3ae
  n_workers: 0
  # hparams
  batch_size: 128
  learning_rate: 1e-3
  eps: 1e-3
  n_mc_samples: 1
  decoder_α_offset: 1e-3
  # ood
  # prior
  tau_ood: 0
  # prior
  prior_α: 2.7
  prior_β: 3e-2
  # misc
  n_trials: 1
  seed: 3
  max_epochs: 200
  # pl trainer
  early_stopping_patience: 200
  log_every_n_steps: 100 # How often to log within steps (defaults to every 50 steps)
  flush_logs_every_n_steps: 100 # How often does the log writes to disc
  progress_bar_refresh_rate: 3 # How often to refresh progress bar (in steps).
  check_val_every_n_epoch: 10 # Check val every n train epochs

- name: v3ae_samples_likelihood_a2_7_b4e-2
  experiment_name: cifar
  model_name: v3ae
  n_workers: 0
  # hparams
  batch_size: 128
  learning_rate: 1e-3
  eps: 1e-3
  n_mc_samples: 1
  decoder_α_offset: 1e-3
  # ood
  # prior
  tau_ood: 0
  # prior
  prior_α: 2.7
  prior_β: 4e-2
  # misc
  n_trials: 1
  seed: 3
  max_epochs: 200
  # pl trainer
  early_stopping_patience: 200
  log_every_n_steps: 100 # How often to log within steps (defaults to every 50 steps)
  flush_logs_every_n_steps: 100 # How often does the log writes to disc
  progress_bar_refresh_rate: 3 # How often to refresh progress bar (in steps).
  check_val_every_n_epoch: 10 # Check val every n train epochs

- name: v3ae_samples_likelihood_a2_7_b5e-2
  experiment_name: cifar
  model_name: v3ae
  n_workers: 0
  # hparams
  batch_size: 128
  learning_rate: 1e-3
  eps: 1e-3
  n_mc_samples: 1
  decoder_α_offset: 1e-3
  # ood
  # prior
  tau_ood: 0
  # prior
  prior_α: 2.7
  prior_β: 5e-2
  # misc
  n_trials: 1
  seed: 3
  max_epochs: 200
  # pl trainer
  early_stopping_patience: 200
  log_every_n_steps: 100 # How often to log within steps (defaults to every 50 steps)
  flush_logs_every_n_steps: 100 # How often does the log writes to disc
  progress_bar_refresh_rate: 3 # How often to refresh progress bar (in steps).
  check_val_every_n_epoch: 10 # Check val every n train epochs

- name: v3ae_samples_likelihood_a2_9_b3e-2
  experiment_name: cifar
  model_name: v3ae
  n_workers: 0
  # hparams
  batch_size: 128
  learning_rate: 1e-3
  eps: 1e-3
  n_mc_samples: 1
  decoder_α_offset: 1e-3
  # ood
  # prior
  tau_ood: 0
  # prior
  prior_α: 2.9
  prior_β: 3e-2
  # misc
  n_trials: 1
  seed: 3
  max_epochs: 200
  # pl trainer
  early_stopping_patience: 200
  log_every_n_steps: 100 # How often to log within steps (defaults to every 50 steps)
  flush_logs_every_n_steps: 100 # How often does the log writes to disc
  progress_bar_refresh_rate: 3 # How often to refresh progress bar (in steps).
  check_val_every_n_epoch: 10 # Check val every n train epochs

- name: v3ae_samples_likelihood_a2_9_b4e-2
  experiment_name: cifar
  model_name: v3ae
  n_workers: 0
  # hparams
  batch_size: 128
  learning_rate: 1e-3
  eps: 1e-3
  n_mc_samples: 1
  decoder_α_offset: 1e-3
  # ood
  # prior
  tau_ood: 0
  # prior
  prior_α: 2.9
  prior_β: 4e-2
  # misc
  n_trials: 1
  seed: 3
  max_epochs: 200
  # pl trainer
  early_stopping_patience: 200
  log_every_n_steps: 100 # How often to log within steps (defaults to every 50 steps)
  flush_logs_every_n_steps: 100 # How often does the log writes to disc
  progress_bar_refresh_rate: 3 # How often to refresh progress bar (in steps).
  check_val_every_n_epoch: 10 # Check val every n train epochs

- name: v3ae_samples_likelihood_a2_9_b5e-2
  experiment_name: cifar
  model_name: v3ae
  n_workers: 0
  # hparams
  batch_size: 128
  learning_rate: 1e-3
  eps: 1e-3
  n_mc_samples: 1
  decoder_α_offset: 1e-3
  # ood
  # prior
  tau_ood: 0
  # prior
  prior_α: 2.9
  prior_β: 5e-2
  # misc
  n_trials: 1
  seed: 3
  max_epochs: 200
  # pl trainer
  early_stopping_patience: 200
  log_every_n_steps: 100 # How often to log within steps (defaults to every 50 steps)
  flush_logs_every_n_steps: 100 # How often does the log writes to disc
  progress_bar_refresh_rate: 3 # How often to refresh progress bar (in steps).
  check_val_every_n_epoch: 10 # Check val every n train epochs
