- name: test_test
  experiment_name: toy
  # hparams
  batch_size: 1024
  hidden_dim: 50
  beta_elbo: 1
  beta_ood: 1
  # ood_x_generation_method: optimised_x_ood_kl_ga # optimised_x_ood_v_optimised
  # prior_alpha: 1.5
  # prior_beta: 10
  # pl trainer
  n_trials: 1
  max_epochs: -1
  log_every_n_steps: 1 # How often to log within steps (defaults to every 50 steps)
  flush_logs_every_n_steps: 1 # How often does the log writes to disc
  progress_bar_refresh_rate: 0 # How often to refresh progress bar (in steps).
  # val_check_interval: 5 # How often to check the validation set.
  check_val_every_n_epoch: 1 # Check val every n train epochs
