- name: test_ens_nn
  model_name: ens_regressor
  experiment_name: toy
  # hparams
  eps: 1e-3
  batch_size: 1024
  hidden_dim: 50
  seed: 2
  n_trials: 1
  max_epochs: -1
  early_stopping_patience: 6000
  log_every_n_steps: 500 # How often to log within steps (defaults to every 50 steps)
  flush_logs_every_n_steps: 500 # How often does the log writes to disc
  progress_bar_refresh_rate: 0 # How often to refresh progress bar (in steps).
  check_val_every_n_epoch: 10 # Check val every n train epochs
