- name: implement_new_pig_gd_aggregate_posterior_29
  experiment_name: fashion_mnist_2d
  model_name: v3ae
  n_workers: 0
  # hparams
  batch_size: 500
  learning_rate: 1e-3
  eps: 1e-3
  n_mc_samples: 2
  digits:
    - 2
    - 9
  # From prior_gamma_per_pixel - for MNIST only
  prior_alpha: 0.43274792054263117 # 0.3927581767454884
  prior_beta: 0.005466103219719339 # 0.0010704155012337458
  # ood
  tau_ood: 0.5
  ood_z_generation_method: gd_aggregate_posterior
  # kde_bandwidth_multiplier: 9
  # misc
  n_trials: 1
  seed: 3
  max_epochs: 10
  # pl trainer
  early_stopping_patience: 50
  log_every_n_steps: 10 # How often to log within steps (defaults to every 50 steps)
  flush_logs_every_n_steps: 10 # How often does the log writes to disc
  progress_bar_refresh_rate: 3 # How often to refresh progress bar (in steps).
  check_val_every_n_epoch: 1 # Check val every n train epochs


- name: implement_new_pig_gd_aggregate_posterior_25
  experiment_name: fashion_mnist_2d
  model_name: v3ae
  n_workers: 0
  # hparams
  batch_size: 500
  learning_rate: 1e-3
  eps: 1e-3
  n_mc_samples: 2
  digits:
    - 2
    - 5
  # From prior_gamma_per_pixel - for MNIST only
  prior_alpha: 0.43274792054263117 # 0.3927581767454884
  prior_beta: 0.005466103219719339 # 0.0010704155012337458
  # ood
  tau_ood: 0.5
  ood_z_generation_method: gd_aggregate_posterior
  # kde_bandwidth_multiplier: 9
  # misc
  n_trials: 1
  seed: 3
  max_epochs: 10
  # pl trainer
  early_stopping_patience: 50
  log_every_n_steps: 10 # How often to log within steps (defaults to every 50 steps)
  flush_logs_every_n_steps: 10 # How often does the log writes to disc
  progress_bar_refresh_rate: 3 # How often to refresh progress bar (in steps).
  check_val_every_n_epoch: 1 # Check val every n train epochs


# - name: test_metrics_v3ae
#   experiment_name: mnist
#   model_name: v3ae
#   n_workers: 0
#   # hparams
#   batch_size: 500
#   learning_rate: 1e-3
#   eps: 1e-6
#   # From prior_gamma_per_pixel - for MNIST only
#   prior_alpha: 1.625
#   prior_beta: 0.0010704155012337458
#   # ood
#   tau_ood: 0.5
#   ood_z_generation_method: kde
#   kde_bandwidth_multiplier: 9
#   # misc
#   n_mc_samples: 1
#   n_trials: 1
#   seed: 3
#   max_epochs: 6
#   # pl trainer
#   early_stopping_patience: 3
#   log_every_n_steps: 3 # How often to log within steps (defaults to every 50 steps)
#   flush_logs_every_n_steps: 50 # How often does the log writes to disc
#   progress_bar_refresh_rate: 3 # How often to refresh progress bar (in steps).
#   check_val_every_n_epoch: 1 # Check val every n train epochs

