- name: vae_test
  experiment_name: cifar
  model_name: vanilla_vae
  n_workers: 0
  # hparams
  batch_size: 128
  learning_rate: 1e-3
  eps: 1e-3
  # misc
  n_trials: 1
  seed: 3
  max_epochs: 20
  # pl trainer
  early_stopping_patience: 50
  log_every_n_steps: 50 # How often to log within steps (defaults to every 50 steps)
  flush_logs_every_n_steps: 50 # How often does the log writes to disc
  progress_bar_refresh_rate: 3 # How often to refresh progress bar (in steps).
  check_val_every_n_epoch: 1 # Check val every n train epochs

- name: v3ae_test
  experiment_name: cifar
  model_name: v3ae
  n_workers: 0
  # hparams
  batch_size: 128
  learning_rate: 1e-3
  eps: 1e-3
  n_mc_samples: 1
  decoder_α_offset: 1e-3
  # ood
  # prior
  tau_ood: 0.5
  ood_z_generation_method: gd_aggregate_posterior
  # prior
  prior_α: 2
  prior_β: 1e-2
  # misc
  n_trials: 1
  seed: 3
  max_epochs: 20
  # pl trainer
  early_stopping_patience: 50
  log_every_n_steps: 50 # How often to log within steps (defaults to every 50 steps)
  flush_logs_every_n_steps: 50 # How often does the log writes to disc
  progress_bar_refresh_rate: 3 # How often to refresh progress bar (in steps).
  check_val_every_n_epoch: 1 # Check val every n train epochs