- name: test_full_run
  experiment_name: mnist
  model_name: vanilla_vae
  n_workers: 4
  # hparams
  batch_size: 256
  # pl trainer
  n_trials: 1
  seed: 3
  max_epochs: 100
  early_stopping_patience: 100
  log_every_n_steps: 3 # How often to log within steps (defaults to every 50 steps)
  flush_logs_every_n_steps: 50 # How often does the log writes to disc
  progress_bar_refresh_rate: 3 # How often to refresh progress bar (in steps).
  check_val_every_n_epoch: 1 # Check val every n train epochs
