- name: vae_test_stl10
  experiment_name: stl10
  model_name: vanilla_vae
  n_workers: 0
  # hparams
  batch_size: 10
  learning_rate: 1e-3
  eps: 1e-3
  latent_dims:
    - 256
  # misc
  n_trials: 1
  seed: 3
  max_epochs: 300
  # pl trainer
  early_stopping_patience: 300
  log_every_n_steps: 50 # How often to log within steps (defaults to every 50 steps)
  flush_logs_every_n_steps: 50 # How often does the log writes to disc
  progress_bar_refresh_rate: 3 # How often to refresh progress bar (in steps).
  check_val_every_n_epoch: 5 # Check val every n train epochs