# Fashion MNIST 2 digits
- name: standard_vae
  experiment_name: fashion_mnist_2d
  model_name: vanilla_vae
  n_workers: 0
  # hparams
  batch_size: 500
  learning_rate: 5e-4
  eps: 1e-3
  n_mc_samples: 3
  latent_dims:
    - 2
  digits:
    - 2
    - 5
  # ood
  # misc
  n_trials: 3
  seed: 3
  max_epochs: 200
  # pl trainer
  early_stopping_patience: 200
  log_every_n_steps: 10 # How often to log within steps (defaults to every 50 steps)
  flush_logs_every_n_steps: 10 # How often does the log writes to disc
  progress_bar_refresh_rate: 3 # How often to refresh progress bar (in steps).
  check_val_every_n_epoch: 1 # Check val every n train epochs

# Fashion MNIST 2D latent space
- name: latent_2d_standard_vae
  experiment_name: fashion_mnist
  model_name: vanilla_vae
  n_workers: 0
  # hparams
  batch_size: 500
  learning_rate: 5e-4
  eps: 1e-3
  n_mc_samples: 3
  latent_dims:
    - 2
  # ood
  # misc
  n_trials: 3
  seed: 3
  max_epochs: 200
  # pl trainer
  early_stopping_patience: 200
  log_every_n_steps: 10 # How often to log within steps (defaults to every 50 steps)
  flush_logs_every_n_steps: 10 # How often does the log writes to disc
  progress_bar_refresh_rate: 3 # How often to refresh progress bar (in steps).
  check_val_every_n_epoch: 1 # Check val every n train epochs


- name: latent_2d_lucky_shot_x100
  experiment_name: fashion_mnist
  model_name: v3ae
  n_workers: 0
  # hparams
  batch_size: 500
  learning_rate: 5e-4
  eps: 1e-3
  n_mc_samples: 3
  latent_dims:
    - 2
  decoder_α_offset: 1e-3
  # ood
  tau_ood: 0.5
  ood_z_generation_method: gd_aggregate_posterior
  # prior
  prior_α: 1.625
  prior_β: 0.001
  prior_extrapolation_x: 100
  # misc
  n_trials: 3
  seed: 3
  max_epochs: 200
  # pl trainer
  early_stopping_patience: 200
  log_every_n_steps: 10 # How often to log within steps (defaults to every 50 steps)
  flush_logs_every_n_steps: 10 # How often does the log writes to disc
  progress_bar_refresh_rate: 3 # How often to refresh progress bar (in steps).
  check_val_every_n_epoch: 1 # Check val every n train epochs
