- name: gaussian_vae
  experiment_name: fashion_mnist
  model_name: vanilla_vae
  n_workers: 0
  # hparams
  batch_size: 500
  learning_rate: 1e-4
  eps: 1e-6
  # From prior_gamma_per_pixel - for MNIST only
  # misc
  n_trials: 1
  seed: 3
  max_epochs: 200
  # pl trainer
  early_stopping_patience: 50
  log_every_n_steps: 50 # How often to log within steps (defaults to every 50 steps)
  flush_logs_every_n_steps: 50 # How often does the log writes to disc
  progress_bar_refresh_rate: 3 # How often to refresh progress bar (in steps).
  check_val_every_n_epoch: 10 # Check val every n train epochs

- name: standard_vv
  experiment_name: fashion_mnist
  model_name: v3ae
  n_workers: 0
  # hparams
  batch_size: 500
  learning_rate: 1e-4
  eps: 1e-6
  # From prior_gamma_per_pixel - for MNIST only
  prior_alpha: 1.567
  prior_beta: 0.005466103219719339
  # misc
  n_mc_samples: 5
  n_trials: 1
  seed: 3
  max_epochs: 200
  # pl trainer
  early_stopping_patience: 50
  log_every_n_steps: 50 # How often to log within steps (defaults to every 50 steps)
  flush_logs_every_n_steps: 50 # How often does the log writes to disc
  progress_bar_refresh_rate: 3 # How often to refresh progress bar (in steps).
  check_val_every_n_epoch: 10 # Check val every n train epochs

- name: robust_vv
  experiment_name: fashion_mnist
  model_name: v3ae
  n_workers: 0
  # hparams
  batch_size: 500
  learning_rate: 1e-4
  eps: 1e-6
  # From prior_gamma_per_pixel - for MNIST only
  prior_alpha: 1.567
  prior_beta: 0.005466103219719339
  # ood
  tau_ood: 0.5
  ood_z_generation_method: kde
  kde_bandwidth_multiplier: 9
  # misc
  n_mc_samples: 5
  n_trials: 1
  seed: 3
  max_epochs: 200
  # pl trainer
  early_stopping_patience: 50
  log_every_n_steps: 50 # How often to log within steps (defaults to every 50 steps)
  flush_logs_every_n_steps: 50 # How often does the log writes to disc
  progress_bar_refresh_rate: 3 # How often to refresh progress bar (in steps).
  check_val_every_n_epoch: 10 # Check val every n train epochs