## ===================
## UCI CCPP

- name: match_vv_mle
  experiment_name: uci_ccpp
  # hparams
  batch_size: 1024
  hidden_dim: 50
  beta_elbo: 0
  beta_ood: 0
  prior_alpha: 1.
  prior_beta: 0.001
  # pl trainer
  n_trials: 20
  max_epochs: -1
  log_every_n_steps: 10 # How often to log within steps (defaults to every 50 steps)
  flush_logs_every_n_steps: 10 # How often does the log writes to disc
  progress_bar_refresh_rate: 0 # How often to refresh progress bar (in steps).
  check_val_every_n_epoch: 1 # Check val every n train epochs

- name: match_vv_standard_elbo
  experiment_name: uci_ccpp
  # hparams
  batch_size: 1024
  hidden_dim: 50
  beta_elbo: 1
  beta_ood: 0
  prior_alpha: 1.
  prior_beta: 0.001
  # pl trainer
  n_trials: 20
  max_epochs: -1
  log_every_n_steps: 10 # How often to log within steps (defaults to every 50 steps)
  flush_logs_every_n_steps: 10 # How often does the log writes to disc
  progress_bar_refresh_rate: 0 # How often to refresh progress bar (in steps).
  check_val_every_n_epoch: 1 # Check val every n train epochs

## ===================
## UCI WINE WHITE

- name: match_vv_mle_sp
  experiment_name: uci_wine_white
  # hparams
  batch_size: 1024
  hidden_dim: 50
  beta_elbo: 0
  beta_ood: 0
  prior_alpha: 1.
  prior_beta: 0.001
  # pl trainer
  n_trials: 20
  max_epochs: -1
  log_every_n_steps: 10 # How often to log within steps (defaults to every 50 steps)
  flush_logs_every_n_steps: 10 # How often does the log writes to disc
  progress_bar_refresh_rate: 0 # How often to refresh progress bar (in steps).
  check_val_every_n_epoch: 1 # Check val every n train epochs

- name: match_vv_standard_elbo_sp
  experiment_name: uci_wine_white
  # hparams
  batch_size: 1024
  hidden_dim: 50
  beta_elbo: 1
  beta_ood: 0
  prior_alpha: 1.
  prior_beta: 0.001
  # pl trainer
  n_trials: 20
  max_epochs: -1
  log_every_n_steps: 10 # How often to log within steps (defaults to every 50 steps)
  flush_logs_every_n_steps: 10 # How often does the log writes to disc
  progress_bar_refresh_rate: 0 # How often to refresh progress bar (in steps).
  check_val_every_n_epoch: 1 # Check val every n train epochs


## ===================
## UCI YACHT

- name: match_vv_mle_sp
  experiment_name: uci_yacht
  # hparams
  batch_size: 1024
  hidden_dim: 50
  beta_elbo: 0
  beta_ood: 0
  prior_alpha: 1.
  prior_beta: 0.001
  # pl trainer
  n_trials: 20
  max_epochs: -1
  log_every_n_steps: 10 # How often to log within steps (defaults to every 50 steps)
  flush_logs_every_n_steps: 10 # How often does the log writes to disc
  progress_bar_refresh_rate: 0 # How often to refresh progress bar (in steps).
  check_val_every_n_epoch: 1 # Check val every n train epochs

- name: match_vv_standard_elbo_sp
  experiment_name: uci_yacht
  # hparams
  batch_size: 1024
  hidden_dim: 50
  beta_elbo: 1
  beta_ood: 0
  prior_alpha: 1.
  prior_beta: 0.001
  # pl trainer
  n_trials: 20
  max_epochs: -1
  log_every_n_steps: 10 # How often to log within steps (defaults to every 50 steps)
  flush_logs_every_n_steps: 10 # How often does the log writes to disc
  progress_bar_refresh_rate: 0 # How often to refresh progress bar (in steps).
  check_val_every_n_epoch: 1 # Check val every n train epochs