- name: hidden_dim_40
  experiment_name: toy
  # hparams
  batch_size: 500
  hidden_dim: 40
  beta_elbo: 1
  beta_ood: 1
  ood_x_generation_method: gaussian_noise_around_x
  prior_alpha: 1.0025
  prior_beta: 0.05
  # pl trainer
  n_trials: 5
  max_epochs: 6000
  log_every_n_steps: 500 # How often to log within steps (defaults to every 50 steps)
  flush_logs_every_n_steps: 500 # How often does the log writes to disc
  progress_bar_refresh_rate: 0 # How often to refresh progress bar (in steps).
  # val_check_interval: 5 # How often to check the validation set.
  check_val_every_n_epoch: 500 # Check val every n train epochs

- name: hidden_dim_25
  experiment_name: toy
  # hparams
  batch_size: 500
  hidden_dim: 25
  beta_elbo: 1
  beta_ood: 1
  ood_x_generation_method: gaussian_noise_around_x
  prior_alpha: 1.0025
  prior_beta: 0.05
  # pl trainer
  n_trials: 5
  max_epochs: 6000
  log_every_n_steps: 500 # How often to log within steps (defaults to every 50 steps)
  flush_logs_every_n_steps: 500 # How often does the log writes to disc
  progress_bar_refresh_rate: 0 # How often to refresh progress bar (in steps).
  # val_check_interval: 5 # How often to check the validation set.
  check_val_every_n_epoch: 500 # Check val every n train epochs

- name: hidden_dim_15
  experiment_name: toy
  # hparams
  batch_size: 500
  hidden_dim: 15
  beta_elbo: 1
  beta_ood: 1
  ood_x_generation_method: gaussian_noise_around_x
  prior_alpha: 1.0025
  prior_beta: 0.05
  # pl trainer
  n_trials: 5
  max_epochs: 6000
  log_every_n_steps: 500 # How often to log within steps (defaults to every 50 steps)
  flush_logs_every_n_steps: 500 # How often does the log writes to disc
  progress_bar_refresh_rate: 0 # How often to refresh progress bar (in steps).
  # val_check_interval: 5 # How often to check the validation set.
  check_val_every_n_epoch: 500 # Check val every n train epochs

- name: hidden_dim_5
  experiment_name: toy
  # hparams
  batch_size: 500
  hidden_dim: 5
  beta_elbo: 1
  beta_ood: 1
  ood_x_generation_method: gaussian_noise_around_x
  prior_alpha: 1.0025
  prior_beta: 0.05
  # pl trainer
  n_trials: 5
  max_epochs: 6000
  log_every_n_steps: 500 # How often to log within steps (defaults to every 50 steps)
  flush_logs_every_n_steps: 500 # How often does the log writes to disc
  progress_bar_refresh_rate: 0 # How often to refresh progress bar (in steps).
  # val_check_interval: 5 # How often to check the validation set.
  check_val_every_n_epoch: 500 # Check val every n train epochs