
# Ours
- name: plot_toy_ours
  experiment_name: toy
  # hparams
  batch_size: 1024
  hidden_dim: 50
  beta_elbo: 0.5
  beta_ood: 0.5
  prior_alpha: 1.025
  prior_beta: 0.5
  ood_x_generation_method: brute_force
  seed: 2
  # pl trainer
  early_stopping_patience: 250
  n_trials: 20
  max_epochs: -1
  log_every_n_steps: 500 # How often to log within steps (defaults to every 50 steps)
  flush_logs_every_n_steps: 50 # How often does the log writes to disc
  progress_bar_refresh_rate: 0 # How often to refresh progress bar (in steps).
  check_val_every_n_epoch: 1 # Check val every n train epochs

- name: plot_toy_ours
  experiment_name: toy_shifted
  # hparams
  batch_size: 1024
  hidden_dim: 50
  beta_elbo: 0.5
  beta_ood: 0.5
  prior_alpha: 1.025
  prior_beta: 0.5
  ood_x_generation_method: brute_force
  # shift
  seed: 2
  shifting_proportion_total: 0.5
  shifting_proportion_k: 0.003
  # pl trainer
  early_stopping_patience: 250
  n_trials: 20
  max_epochs: -1
  log_every_n_steps: 500 # How often to log within steps (defaults to every 50 steps)
  flush_logs_every_n_steps: 50 # How often does the log writes to disc
  progress_bar_refresh_rate: 0 # How often to refresh progress bar (in steps).
  check_val_every_n_epoch: 1 # Check val every n train epochs

# Beta OOD
- name: plot_toy_ours_beta_02
  experiment_name: toy
  # hparams
  batch_size: 1024
  hidden_dim: 50
  beta_elbo: 0.5
  beta_ood: 0.2
  prior_alpha: 1.025
  prior_beta: 0.5
  ood_x_generation_method: brute_force
  seed: 2
  # pl trainer
  early_stopping_patience: 250
  n_trials: 20
  max_epochs: -1
  log_every_n_steps: 500 # How often to log within steps (defaults to every 50 steps)
  flush_logs_every_n_steps: 50 # How often does the log writes to disc
  progress_bar_refresh_rate: 0 # How often to refresh progress bar (in steps).
  check_val_every_n_epoch: 1 # Check val every n train epochs

- name: plot_toy_ours_beta_08
  experiment_name: toy
  # hparams
  batch_size: 1024
  hidden_dim: 50
  beta_elbo: 0.5
  beta_ood: 0.8
  prior_alpha: 1.025
  prior_beta: 0.5
  ood_x_generation_method: brute_force
  seed: 2
  # pl trainer
  early_stopping_patience: 250
  n_trials: 20
  max_epochs: -1
  log_every_n_steps: 500 # How often to log within steps (defaults to every 50 steps)
  flush_logs_every_n_steps: 50 # How often does the log writes to disc
  progress_bar_refresh_rate: 0 # How often to refresh progress bar (in steps).
  check_val_every_n_epoch: 1 # Check val every n train epochs

- name: plot_toy_ours_beta_099
  experiment_name: toy
  # hparams
  batch_size: 1024
  hidden_dim: 50
  beta_elbo: 0.5
  beta_ood: 0.99
  prior_alpha: 1.025
  prior_beta: 0.5
  ood_x_generation_method: brute_force
  seed: 2
  # pl trainer
  early_stopping_patience: 250
  n_trials: 20
  max_epochs: -1
  log_every_n_steps: 500 # How often to log within steps (defaults to every 50 steps)
  flush_logs_every_n_steps: 50 # How often does the log writes to disc
  progress_bar_refresh_rate: 0 # How often to refresh progress bar (in steps).
  check_val_every_n_epoch: 1 # Check val every n train epochs

# Other approaches
- name: plot_toy_gaussian_noise
  experiment_name: toy
  # hparams
  batch_size: 1024
  hidden_dim: 50
  beta_elbo: 0.5
  beta_ood: 0.5
  prior_alpha: 1.025
  prior_beta: 0.5
  ood_x_generation_method: gaussian_noise
  seed: 2
  # pl trainer
  early_stopping_patience: 250
  n_trials: 20
  max_epochs: -1
  log_every_n_steps: 500 # How often to log within steps (defaults to every 50 steps)
  flush_logs_every_n_steps: 50 # How often does the log writes to disc
  progress_bar_refresh_rate: 0 # How often to refresh progress bar (in steps).
  check_val_every_n_epoch: 1 # Check val every n train epochs

- name: plot_toy_adversarial
  experiment_name: toy
  # hparams
  batch_size: 1024
  hidden_dim: 50
  beta_elbo: 0.5
  beta_ood: 0.5
  prior_alpha: 1.025
  prior_beta: 0.5
  ood_x_generation_method: adversarial
  seed: 2
  # pl trainer
  early_stopping_patience: 250
  n_trials: 20
  max_epochs: -1
  log_every_n_steps: 500 # How often to log within steps (defaults to every 50 steps)
  flush_logs_every_n_steps: 50 # How often does the log writes to disc
  progress_bar_refresh_rate: 0 # How often to refresh progress bar (in steps).
  check_val_every_n_epoch: 1 # Check val every n train epochs






