- name: a_1_0025_b_0_05_reverse_kl
  experiment_name: toy
  # hparams
  batch_size: 500
  hidden_dim: 50
  beta_elbo: 1
  beta_ood: 1
  ood_x_generation_method: gaussian_noise_around_x
  prior_alpha: 1.0025
  prior_beta: 0.05
  # pl trainer
  n_trials: 10
  max_epochs: 6000
  log_every_n_steps: 500 # How often to log within steps (defaults to every 50 steps)
  flush_logs_every_n_steps: 500 # How often does the log writes to disc
  progress_bar_refresh_rate: 0 # How often to refresh progress bar (in steps).
  # val_check_interval: 5 # How often to check the validation set.
  check_val_every_n_epoch: 500 # Check val every n train epochs

# - name: a_1_025_b_0_5_reverse_kl
#   experiment_name: toy
#   # hparams
#   batch_size: 500
#   hidden_dim: 50
#   beta_elbo: 1
#   beta_ood: 1
#   ood_x_generation_method: gaussian_noise_around_x
#   prior_alpha: 1.025
#   prior_beta: 0.5
#   # pl trainer
#   n_trials: 10
#   max_epochs: 6000
#   log_every_n_steps: 500 # How often to log within steps (defaults to every 50 steps)
#   flush_logs_every_n_steps: 500 # How often does the log writes to disc
#   progress_bar_refresh_rate: 0 # How often to refresh progress bar (in steps).
#   # val_check_interval: 5 # How often to check the validation set.
#   check_val_every_n_epoch: 500 # Check val every n train epochs

# - name: a_1_05_b_1
#   experiment_name: toy
#   # hparams
#   batch_size: 500
#   hidden_dim: 50
#   beta_elbo: 1
#   beta_ood: 1
#   ood_x_generation_method: gaussian_noise_around_x
#   prior_alpha: 1.05
#   prior_beta: 1
#   # pl trainer
#   n_trials: 10
#   max_epochs: 6000
#   log_every_n_steps: 500 # How often to log within steps (defaults to every 50 steps)
#   flush_logs_every_n_steps: 500 # How often does the log writes to disc
#   progress_bar_refresh_rate: 0 # How often to refresh progress bar (in steps).
#   # val_check_interval: 5 # How often to check the validation set.
#   check_val_every_n_epoch: 500 # Check val every n train epochs

# - name: a_1_25_b_5
#   experiment_name: toy
#   # hparams
#   batch_size: 500
#   hidden_dim: 50
#   beta_elbo: 1
#   beta_ood: 1
#   ood_x_generation_method: gaussian_noise_around_x
#   prior_alpha: 1.25
#   prior_beta: 5
#   # pl trainer
#   n_trials: 10
#   max_epochs: 6000
#   log_every_n_steps: 500 # How often to log within steps (defaults to every 50 steps)
#   flush_logs_every_n_steps: 500 # How often does the log writes to disc
#   progress_bar_refresh_rate: 0 # How often to refresh progress bar (in steps).
#   # val_check_interval: 5 # How often to check the validation set.
#   check_val_every_n_epoch: 500 # Check val every n train epochs

# - name: a_1_5_b_10
#   experiment_name: toy
#   # hparams
#   batch_size: 500
#   hidden_dim: 50
#   beta_elbo: 1
#   beta_ood: 1
#   ood_x_generation_method: gaussian_noise_around_x
#   prior_alpha: 1.5
#   prior_beta: 10
#   # pl trainer
#   n_trials: 10
#   max_epochs: 6000
#   log_every_n_steps: 500 # How often to log within steps (defaults to every 50 steps)
#   flush_logs_every_n_steps: 500 # How often does the log writes to disc
#   progress_bar_refresh_rate: 0 # How often to refresh progress bar (in steps).
#   # val_check_interval: 5 # How often to check the validation set.
#   check_val_every_n_epoch: 500 # Check val every n train epochs
