
# No shift - OK
# - name: benchmark_standard_elbo_st
#   experiment_name: uci_superconduct
#   # hparams
#   batch_size: 1024
#   hidden_dim: 50
#   beta_elbo: 0.5
#   beta_ood: 0
#   prior_alpha: 1.05
#   prior_beta: 0.5
#   # shift
#   seed: 3
#   # shifting_proportion_total: 1e-64
#   # shifting_proportion_k: 0.00005
#   # pl trainer
#   n_trials: 20
#   max_epochs: -1
#   log_every_n_steps: 500 # How often to log within steps (defaults to every 50 steps)
#   flush_logs_every_n_steps: 50 # How often does the log writes to disc
#   progress_bar_refresh_rate: 0 # How often to refresh progress bar (in steps).
#   check_val_every_n_epoch: 1 # Check val every n train epochs

# - name: benchmark_adversarial_st
#   experiment_name: uci_superconduct
#   # hparams
#   batch_size: 1024
#   hidden_dim: 50
#   beta_elbo: 0.5
#   beta_ood: 0
#   prior_alpha: 1.05
#   prior_beta: 0.5
#   ood_x_generation_method: adversarial
#   split_training: True
#   # shift
#   seed: 3
#   # shifting_proportion_total: 1e-64
#   # shifting_proportion_k: 0.00005
#   # pl trainer
#   n_trials: 20
#   max_epochs: -1
#   log_every_n_steps: 500 # How often to log within steps (defaults to every 50 steps)
#   flush_logs_every_n_steps: 50 # How often does the log writes to disc
#   progress_bar_refresh_rate: 0 # How often to refresh progress bar (in steps).
#   check_val_every_n_epoch: 1 # Check val every n train epochs

# - name: benchmark_gaussian_noise_st
#   experiment_name: uci_superconduct
#   # hparams
#   batch_size: 1024
#   hidden_dim: 50
#   beta_elbo: 0.5
#   beta_ood: 0
#   prior_alpha: 1.05
#   prior_beta: 0.5
#   ood_x_generation_method: gaussian_noise
#   split_training: True
#   # shift
#   seed: 3
#   # shifting_proportion_total: 1e-64
#   # shifting_proportion_k: 0.00005
#   # pl trainer
#   n_trials: 20
#   max_epochs: -1
#   log_every_n_steps: 500 # How often to log within steps (defaults to every 50 steps)
#   flush_logs_every_n_steps: 50 # How often does the log writes to disc
#   progress_bar_refresh_rate: 0 # How often to refresh progress bar (in steps).
#   check_val_every_n_epoch: 1 # Check val every n train epochs

# 1e-64
# - name: benchmark_standard_elbo_1e-64_st
#   experiment_name: uci_superconduct_shifted
#   # hparams
#   batch_size: 1024
#   hidden_dim: 50
#   beta_elbo: 0.5
#   beta_ood: 0
#   prior_alpha: 1.05
#   prior_beta: 0.5
#   # shift
#   seed: 3
#   shifting_proportion_total: 1e-64
#   shifting_proportion_k: 0.00005
#   # pl trainer
#   n_trials: 20
#   max_epochs: -1
#   log_every_n_steps: 500 # How often to log within steps (defaults to every 50 steps)
#   flush_logs_every_n_steps: 50 # How often does the log writes to disc
#   progress_bar_refresh_rate: 0 # How often to refresh progress bar (in steps).
#   check_val_every_n_epoch: 1 # Check val every n train epochs

- name: benchmark_gaussian_noise_1e-64_st
  experiment_name: uci_superconduct_shifted
  # hparams
  batch_size: 1024
  hidden_dim: 50
  beta_elbo: 0.5
  beta_ood: 0.5
  prior_alpha: 1.05
  prior_beta: 0.5
  ood_x_generation_method: gaussian_noise
  split_training: True
  # shift
  seed: 3
  shifting_proportion_total: 1e-64
  shifting_proportion_k: 0.00005
  # pl trainer
  n_trials: 20
  max_epochs: -1
  log_every_n_steps: 500 # How often to log within steps (defaults to every 50 steps)
  flush_logs_every_n_steps: 50 # How often does the log writes to disc
  progress_bar_refresh_rate: 0 # How often to refresh progress bar (in steps).
  check_val_every_n_epoch: 1 # Check val every n train epochs

- name: benchmark_adversarial_1e-64_st
  experiment_name: uci_superconduct_shifted
  # hparams
  batch_size: 1024
  hidden_dim: 50
  beta_elbo: 0.5
  beta_ood: 0.5
  prior_alpha: 1.05
  prior_beta: 0.5
  ood_x_generation_method: adversarial
  split_training: True
  # shift
  seed: 3
  shifting_proportion_total: 1e-64
  shifting_proportion_k: 0.00005
  # pl trainer
  n_trials: 20
  max_epochs: -1
  log_every_n_steps: 500 # How often to log within steps (defaults to every 50 steps)
  flush_logs_every_n_steps: 50 # How often does the log writes to disc
  progress_bar_refresh_rate: 0 # How often to refresh progress bar (in steps).
  check_val_every_n_epoch: 1 # Check val every n train epochs

# 1e-32
# - name: benchmark_standard_elbo_1e-32_st
#   experiment_name: uci_superconduct_shifted
#   # hparams
#   batch_size: 1024
#   hidden_dim: 50
#   beta_elbo: 0.5
#   beta_ood: 0
#   prior_alpha: 1.05
#   prior_beta: 0.5
#   # shift
#   seed: 3
#   shifting_proportion_total: 1e-32
#   shifting_proportion_k: 0.00005
#   # pl trainer
#   n_trials: 20
#   max_epochs: -1
#   log_every_n_steps: 500 # How often to log within steps (defaults to every 50 steps)
#   flush_logs_every_n_steps: 50 # How often does the log writes to disc
#   progress_bar_refresh_rate: 0 # How often to refresh progress bar (in steps).
#   check_val_every_n_epoch: 1 # Check val every n train epochs

- name: benchmark_gaussian_noise_1e-32_st
  experiment_name: uci_superconduct_shifted
  # hparams
  batch_size: 1024
  hidden_dim: 50
  beta_elbo: 0.5
  beta_ood: 0.5
  prior_alpha: 1.05
  prior_beta: 0.5
  ood_x_generation_method: gaussian_noise
  split_training: True
  # shift
  seed: 3
  shifting_proportion_total: 1e-32
  shifting_proportion_k: 0.00005
  # pl trainer
  n_trials: 20
  max_epochs: -1
  log_every_n_steps: 500 # How often to log within steps (defaults to every 50 steps)
  flush_logs_every_n_steps: 50 # How often does the log writes to disc
  progress_bar_refresh_rate: 0 # How often to refresh progress bar (in steps).
  check_val_every_n_epoch: 1 # Check val every n train epochs

- name: benchmark_adversarial_1e-32_st
  experiment_name: uci_superconduct_shifted
  # hparams
  batch_size: 1024
  hidden_dim: 50
  beta_elbo: 0.5
  beta_ood: 0.5
  prior_alpha: 1.05
  prior_beta: 0.5
  ood_x_generation_method: adversarial
  split_training: True
  # shift
  seed: 3
  shifting_proportion_total: 1e-32
  shifting_proportion_k: 0.00005
  # pl trainer
  n_trials: 20
  max_epochs: -1
  log_every_n_steps: 500 # How often to log within steps (defaults to every 50 steps)
  flush_logs_every_n_steps: 50 # How often does the log writes to disc
  progress_bar_refresh_rate: 0 # How often to refresh progress bar (in steps).
  check_val_every_n_epoch: 1 # Check val every n train epochs

# 1e-16
# - name: benchmark_standard_elbo_1e-16_st
#   experiment_name: uci_superconduct_shifted
#   # hparams
#   batch_size: 1024
#   hidden_dim: 50
#   beta_elbo: 0.5
#   beta_ood: 0
#   prior_alpha: 1.05
#   prior_beta: 0.5
#   # shift
#   seed: 3
#   shifting_proportion_total: 1e-16
#   shifting_proportion_k: 0.00005
#   # pl trainer
#   n_trials: 20
#   max_epochs: -1
#   log_every_n_steps: 500 # How often to log within steps (defaults to every 50 steps)
#   flush_logs_every_n_steps: 50 # How often does the log writes to disc
#   progress_bar_refresh_rate: 0 # How often to refresh progress bar (in steps).
#   check_val_every_n_epoch: 1 # Check val every n train epochs

- name: benchmark_gaussian_noise_1e-16_st
  experiment_name: uci_superconduct_shifted
  # hparams
  batch_size: 1024
  hidden_dim: 50
  beta_elbo: 0.5
  beta_ood: 0.5
  prior_alpha: 1.05
  prior_beta: 0.5
  ood_x_generation_method: gaussian_noise
  split_training: True
  # shift
  seed: 3
  shifting_proportion_total: 1e-16
  shifting_proportion_k: 0.00005
  # pl trainer
  n_trials: 20
  max_epochs: -1
  log_every_n_steps: 500 # How often to log within steps (defaults to every 50 steps)
  flush_logs_every_n_steps: 50 # How often does the log writes to disc
  progress_bar_refresh_rate: 0 # How often to refresh progress bar (in steps).
  check_val_every_n_epoch: 1 # Check val every n train epochs

- name: benchmark_adversarial_1e-16_st
  experiment_name: uci_superconduct_shifted
  # hparams
  batch_size: 1024
  hidden_dim: 50
  beta_elbo: 0.5
  beta_ood: 0.5
  prior_alpha: 1.05
  prior_beta: 0.5
  ood_x_generation_method: adversarial
  split_training: True
  # shift
  seed: 3
  shifting_proportion_total: 1e-16
  shifting_proportion_k: 0.00005
  # pl trainer
  n_trials: 20
  max_epochs: -1
  log_every_n_steps: 500 # How often to log within steps (defaults to every 50 steps)
  flush_logs_every_n_steps: 50 # How often does the log writes to disc
  progress_bar_refresh_rate: 0 # How often to refresh progress bar (in steps).
  check_val_every_n_epoch: 1 # Check val every n train epochs

# 1e-4
# - name: benchmark_standard_elbo_1e-4_st
#   experiment_name: uci_superconduct_shifted
#   # hparams
#   batch_size: 1024
#   hidden_dim: 50
#   beta_elbo: 0.5
#   beta_ood: 0
#   prior_alpha: 1.05
#   prior_beta: 0.5
#   # shift
#   seed: 3
#   shifting_proportion_total: 1e-4
#   shifting_proportion_k: 0.00005
#   # pl trainer
#   n_trials: 20
#   max_epochs: -1
#   log_every_n_steps: 500 # How often to log within steps (defaults to every 50 steps)
#   flush_logs_every_n_steps: 50 # How often does the log writes to disc
#   progress_bar_refresh_rate: 0 # How often to refresh progress bar (in steps).
#   check_val_every_n_epoch: 1 # Check val every n train epochs

- name: benchmark_gaussian_noise_1e-4_st
  experiment_name: uci_superconduct_shifted
  # hparams
  batch_size: 1024
  hidden_dim: 50
  beta_elbo: 0.5
  beta_ood: 0.5
  prior_alpha: 1.05
  prior_beta: 0.5
  ood_x_generation_method: gaussian_noise
  split_training: True
  # shift
  seed: 3
  shifting_proportion_total: 1e-4
  shifting_proportion_k: 0.00005
  # pl trainer
  n_trials: 20
  max_epochs: -1
  log_every_n_steps: 500 # How often to log within steps (defaults to every 50 steps)
  flush_logs_every_n_steps: 50 # How often does the log writes to disc
  progress_bar_refresh_rate: 0 # How often to refresh progress bar (in steps).
  check_val_every_n_epoch: 1 # Check val every n train epochs

- name: benchmark_adversarial_1e-4_st
  experiment_name: uci_superconduct_shifted
  # hparams
  batch_size: 1024
  hidden_dim: 50
  beta_elbo: 0.5
  beta_ood: 0.5
  prior_alpha: 1.05
  prior_beta: 0.5
  ood_x_generation_method: adversarial
  split_training: True
  # shift
  seed: 3
  shifting_proportion_total: 1e-4
  shifting_proportion_k: 0.00005
  # pl trainer
  n_trials: 20
  max_epochs: -1
  log_every_n_steps: 500 # How often to log within steps (defaults to every 50 steps)
  flush_logs_every_n_steps: 50 # How often does the log writes to disc
  progress_bar_refresh_rate: 0 # How often to refresh progress bar (in steps).
  check_val_every_n_epoch: 1 # Check val every n train epochs

# 1e-2
# - name: benchmark_standard_elbo_1e-2_st
#   experiment_name: uci_superconduct_shifted
#   # hparams
#   batch_size: 1024
#   hidden_dim: 50
#   beta_elbo: 0.5
#   beta_ood: 0
#   prior_alpha: 1.05
#   prior_beta: 0.5
#   # shift
#   seed: 3
#   shifting_proportion_total: 1e-2
#   shifting_proportion_k: 0.00005
#   # pl trainer
#   n_trials: 20
#   max_epochs: -1
#   log_every_n_steps: 500 # How often to log within steps (defaults to every 50 steps)
#   flush_logs_every_n_steps: 50 # How often does the log writes to disc
#   progress_bar_refresh_rate: 0 # How often to refresh progress bar (in steps).
#   check_val_every_n_epoch: 1 # Check val every n train epochs

- name: benchmark_gaussian_noise_1e-2_st
  experiment_name: uci_superconduct_shifted
  # hparams
  batch_size: 1024
  hidden_dim: 50
  beta_elbo: 0.5
  beta_ood: 0.5
  prior_alpha: 1.05
  prior_beta: 0.5
  ood_x_generation_method: gaussian_noise
  split_training: True
  # shift
  seed: 3
  shifting_proportion_total: 1e-2
  shifting_proportion_k: 0.00005
  # pl trainer
  n_trials: 20
  max_epochs: -1
  log_every_n_steps: 500 # How often to log within steps (defaults to every 50 steps)
  flush_logs_every_n_steps: 50 # How often does the log writes to disc
  progress_bar_refresh_rate: 0 # How often to refresh progress bar (in steps).
  check_val_every_n_epoch: 1 # Check val every n train epochs

- name: benchmark_adversarial_1e-2_st
  experiment_name: uci_superconduct_shifted
  # hparams
  batch_size: 1024
  hidden_dim: 50
  beta_elbo: 0.5
  beta_ood: 0.5
  prior_alpha: 1.05
  prior_beta: 0.5
  ood_x_generation_method: adversarial
  split_training: True
  # shift
  seed: 3
  shifting_proportion_total: 1e-2
  shifting_proportion_k: 0.00005
  # pl trainer
  n_trials: 20
  max_epochs: -1
  log_every_n_steps: 500 # How often to log within steps (defaults to every 50 steps)
  flush_logs_every_n_steps: 50 # How often does the log writes to disc
  progress_bar_refresh_rate: 0 # How often to refresh progress bar (in steps).
  check_val_every_n_epoch: 1 # Check val every n train epochs

# 1e3
# - name: benchmark_standard_elbo_1e3_st
#   experiment_name: uci_superconduct_shifted
#   # hparams
#   batch_size: 1024
#   hidden_dim: 50
#   beta_elbo: 0.5
#   beta_ood: 0
#   prior_alpha: 1.05
#   prior_beta: 0.5
#   # shift
#   seed: 3
#   shifting_proportion_total: 1e3
#   shifting_proportion_k: 0.00005
#   # pl trainer
#   n_trials: 20
#   max_epochs: -1
#   log_every_n_steps: 500 # How often to log within steps (defaults to every 50 steps)
#   flush_logs_every_n_steps: 50 # How often does the log writes to disc
#   progress_bar_refresh_rate: 0 # How often to refresh progress bar (in steps).
#   check_val_every_n_epoch: 1 # Check val every n train epochs

- name: benchmark_gaussian_noise_1e3_st
  experiment_name: uci_superconduct_shifted
  # hparams
  batch_size: 1024
  hidden_dim: 50
  beta_elbo: 0.5
  beta_ood: 0.5
  prior_alpha: 1.05
  prior_beta: 0.5
  ood_x_generation_method: gaussian_noise
  split_training: True
  # shift
  seed: 3
  shifting_proportion_total: 1e3
  shifting_proportion_k: 0.00005
  # pl trainer
  n_trials: 20
  max_epochs: -1
  log_every_n_steps: 500 # How often to log within steps (defaults to every 50 steps)
  flush_logs_every_n_steps: 50 # How often does the log writes to disc
  progress_bar_refresh_rate: 0 # How often to refresh progress bar (in steps).
  check_val_every_n_epoch: 1 # Check val every n train epochs

- name: benchmark_adversarial_1e3_st
  experiment_name: uci_superconduct_shifted
  # hparams
  batch_size: 1024
  hidden_dim: 50
  beta_elbo: 0.5
  beta_ood: 0.5
  prior_alpha: 1.05
  prior_beta: 0.5
  ood_x_generation_method: adversarial
  split_training: True
  # shift
  seed: 3
  shifting_proportion_total: 1e3
  shifting_proportion_k: 0.00005
  # pl trainer
  n_trials: 20
  max_epochs: -1
  log_every_n_steps: 500 # How often to log within steps (defaults to every 50 steps)
  flush_logs_every_n_steps: 50 # How often does the log writes to disc
  progress_bar_refresh_rate: 0 # How often to refresh progress bar (in steps).
  check_val_every_n_epoch: 1 # Check val every n train epochs
