- name: vv_match_base
  experiment_name: mnist
  model_name: v3ae
  n_workers: 4
  # hparams
  batch_size: 256
  learning_rate: 5e-5
  eps: 1e-2
  # From prior_gamma_per_pixel - for MNIST only
  prior_alpha: 0.3927581767454884
  prior_beta: 0.0010704155012337458
  # misc
  n_mc_samples: 1
  n_trials: 1
  seed: 3
  max_epochs: 500
  # pl trainer
  early_stopping_patience: 50
  log_every_n_steps: 3 # How often to log within steps (defaults to every 50 steps)
  flush_logs_every_n_steps: 50 # How often does the log writes to disc
  progress_bar_refresh_rate: 3 # How often to refresh progress bar (in steps).
  check_val_every_n_epoch: 5 # Check val every n train epochs

- name: vv_match_eps
  experiment_name: mnist
  model_name: v3ae
  n_workers: 4
  # hparams
  batch_size: 256
  learning_rate: 5e-5
  eps: 1e-3
  # From prior_gamma_per_pixel - for MNIST only
  prior_alpha: 0.3927581767454884
  prior_beta: 0.0010704155012337458
  # misc
  n_mc_samples: 1
  n_trials: 1
  seed: 3
  max_epochs: 500
  # pl trainer
  early_stopping_patience: 50
  log_every_n_steps: 3 # How often to log within steps (defaults to every 50 steps)
  flush_logs_every_n_steps: 50 # How often does the log writes to disc
  progress_bar_refresh_rate: 3 # How often to refresh progress bar (in steps).
  check_val_every_n_epoch: 5 # Check val every n train epochs

- name: vv_match_n_samples
  experiment_name: mnist
  model_name: v3ae
  n_workers: 4
  # hparams
  batch_size: 256
  learning_rate: 5e-5
  eps: 1e-2
  # From prior_gamma_per_pixel - for MNIST only
  prior_alpha: 0.3927581767454884
  prior_beta: 0.0010704155012337458
  # misc
  n_mc_samples: 20
  n_trials: 1
  seed: 3
  max_epochs: 500
  # pl trainer
  early_stopping_patience: 50
  log_every_n_steps: 3 # How often to log within steps (defaults to every 50 steps)
  flush_logs_every_n_steps: 50 # How often does the log writes to disc
  progress_bar_refresh_rate: 3 # How often to refresh progress bar (in steps).
  check_val_every_n_epoch: 5 # Check val every n train epochs

- name: vv_match_eps_n_samples
  experiment_name: mnist
  model_name: v3ae
  n_workers: 4
  # hparams
  batch_size: 256
  learning_rate: 5e-5
  eps: 1e-3
  # From prior_gamma_per_pixel - for MNIST only
  prior_alpha: 0.3927581767454884
  prior_beta: 0.0010704155012337458
  # misc
  n_mc_samples: 20
  n_trials: 1
  seed: 3
  max_epochs: 500
  # pl trainer
  early_stopping_patience: 50
  log_every_n_steps: 3 # How often to log within steps (defaults to every 50 steps)
  flush_logs_every_n_steps: 50 # How often does the log writes to disc
  progress_bar_refresh_rate: 3 # How often to refresh progress bar (in steps).
  check_val_every_n_epoch: 5 # Check val every n train epochs