- name: z_dim_30
  experiment_name: cifar
  model_name: vanilla_vae
  n_workers: 0
  # hparams
  batch_size: 128
  learning_rate: 1e-3
  eps: 1e-3
  latent_dims:
  - 30
  # misc
  n_trials: 2
  seed: 3
  max_epochs: 100
  # pl trainer
  early_stopping_patience: 200
  log_every_n_steps: 10 # How often to log within steps (defaults to every 50 steps)
  flush_logs_every_n_steps: 10 # How often does the log writes to disc
  progress_bar_refresh_rate: 3 # How often to refresh progress bar (in steps).
  check_val_every_n_epoch: 3 # Check val every n train epochs

- name: z_dim_60
  experiment_name: cifar
  model_name: vanilla_vae
  n_workers: 0
  # hparams
  batch_size: 128
  learning_rate: 1e-3
  eps: 1e-3
  latent_dims:
  - 60
  # misc
  n_trials: 2
  seed: 3
  max_epochs: 100
  # pl trainer
  early_stopping_patience: 200
  log_every_n_steps: 10 # How often to log within steps (defaults to every 50 steps)
  flush_logs_every_n_steps: 10 # How often does the log writes to disc
  progress_bar_refresh_rate: 3 # How often to refresh progress bar (in steps).
  check_val_every_n_epoch: 3 # Check val every n train epochs


- name: eps_5e-3
  experiment_name: cifar
  model_name: vanilla_vae
  n_workers: 0
  # hparams
  batch_size: 128
  learning_rate: 1e-3
  eps: 5e-3
  latent_dims:
  - 128
  # misc
  n_trials: 2
  seed: 3
  max_epochs: 100
  # pl trainer
  early_stopping_patience: 200
  log_every_n_steps: 10 # How often to log within steps (defaults to every 50 steps)
  flush_logs_every_n_steps: 10 # How often does the log writes to disc
  progress_bar_refresh_rate: 3 # How often to refresh progress bar (in steps).
  check_val_every_n_epoch: 3 # Check val every n train epochs

- name: eps_5e-4
  experiment_name: cifar
  model_name: vanilla_vae
  n_workers: 0
  # hparams
  batch_size: 128
  learning_rate: 1e-3
  eps: 5e-4
  latent_dims:
  - 128
  # misc
  n_trials: 2
  seed: 3
  max_epochs: 100
  # pl trainer
  early_stopping_patience: 200
  log_every_n_steps: 10 # How often to log within steps (defaults to every 50 steps)
  flush_logs_every_n_steps: 10 # How often does the log writes to disc
  progress_bar_refresh_rate: 3 # How often to refresh progress bar (in steps).
  check_val_every_n_epoch: 3 # Check val every n train epochs