- name: test_cifar
  experiment_name: cifar
  model_name: vanilla_vae
  n_workers: 0
  # hparams
  batch_size: 500
  learning_rate: 5e-4
  eps: 1e-3
  # misc
  n_trials: 1
  seed: 3
  max_epochs: 3
  # pl trainer
  early_stopping_patience: 200
  log_every_n_steps: 10 # How often to log within steps (defaults to every 50 steps)
  flush_logs_every_n_steps: 10 # How often does the log writes to disc
  progress_bar_refresh_rate: 3 # How often to refresh progress bar (in steps).
  check_val_every_n_epoch: 1 # Check val every n train epochs