# %
# Fashion-MNIST

# %
# Prior
- name: b_search_prior_0001
  experiment_name: fashion_mnist_2d
  model_name: v3ae
  n_workers: 0
  # hparams
  batch_size: 500
  learning_rate: 5e-4
  eps: 1e-3
  n_mc_samples: 3
  digits:
    - 2
    - 5
  # ood
  tau_ood: 0.5
  ood_z_generation_method: gd_prior
  prior_b: 0.001
  # misc
  n_trials: 1
  seed: 3
  max_epochs: 200
  # pl trainer
  early_stopping_patience: 200
  log_every_n_steps: 10 # How often to log within steps (defaults to every 50 steps)
  flush_logs_every_n_steps: 10 # How often does the log writes to disc
  progress_bar_refresh_rate: 3 # How often to refresh progress bar (in steps).
  check_val_every_n_epoch: 1 # Check val every n train epochs

- name: b_search_prior_0004
  experiment_name: fashion_mnist_2d
  model_name: v3ae
  n_workers: 0
  # hparams
  batch_size: 500
  learning_rate: 5e-4
  eps: 1e-3
  n_mc_samples: 3
  digits:
    - 2
    - 5
  # ood
  tau_ood: 0.5
  ood_z_generation_method: gd_prior
  prior_b: 0.004
  # misc
  n_trials: 1
  seed: 3
  max_epochs: 200
  # pl trainer
  early_stopping_patience: 200
  log_every_n_steps: 10 # How often to log within steps (defaults to every 50 steps)
  flush_logs_every_n_steps: 10 # How often does the log writes to disc
  progress_bar_refresh_rate: 3 # How often to refresh progress bar (in steps).
  check_val_every_n_epoch: 1 # Check val every n train epochs

- name: b_search_prior_0016
  experiment_name: fashion_mnist_2d
  model_name: v3ae
  n_workers: 0
  # hparams
  batch_size: 500
  learning_rate: 5e-4
  eps: 1e-3
  n_mc_samples: 3
  digits:
    - 2
    - 5
  # ood
  tau_ood: 0.5
  ood_z_generation_method: gd_prior
  prior_b: 0.016
  # misc
  n_trials: 1
  seed: 3
  max_epochs: 200
  # pl trainer
  early_stopping_patience: 200
  log_every_n_steps: 10 # How often to log within steps (defaults to every 50 steps)
  flush_logs_every_n_steps: 10 # How often does the log writes to disc
  progress_bar_refresh_rate: 3 # How often to refresh progress bar (in steps).
  check_val_every_n_epoch: 1 # Check val every n train epochs

- name: b_search_prior_007
  experiment_name: fashion_mnist_2d
  model_name: v3ae
  n_workers: 0
  # hparams
  batch_size: 500
  learning_rate: 5e-4
  eps: 1e-3
  n_mc_samples: 3
  digits:
    - 2
    - 5
  # ood
  tau_ood: 0.5
  ood_z_generation_method: gd_prior
  prior_b: 0.07
  # misc
  n_trials: 1
  seed: 3
  max_epochs: 200
  # pl trainer
  early_stopping_patience: 200
  log_every_n_steps: 10 # How often to log within steps (defaults to every 50 steps)
  flush_logs_every_n_steps: 10 # How often does the log writes to disc
  progress_bar_refresh_rate: 3 # How often to refresh progress bar (in steps).
  check_val_every_n_epoch: 1 # Check val every n train epochs

- name: b_search_prior_025
  experiment_name: fashion_mnist_2d
  model_name: v3ae
  n_workers: 0
  # hparams
  batch_size: 500
  learning_rate: 5e-4
  eps: 1e-3
  n_mc_samples: 3
  digits:
    - 2
    - 5
  # ood
  tau_ood: 0.5
  ood_z_generation_method: gd_prior
  prior_b: 0.25
  # misc
  n_trials: 1
  seed: 3
  max_epochs: 200
  # pl trainer
  early_stopping_patience: 200
  log_every_n_steps: 10 # How often to log within steps (defaults to every 50 steps)
  flush_logs_every_n_steps: 10 # How often does the log writes to disc
  progress_bar_refresh_rate: 3 # How often to refresh progress bar (in steps).
  check_val_every_n_epoch: 1 # Check val every n train epochs

# %
# Posterior
- name: b_search_aggregate_posterior_0001
  experiment_name: fashion_mnist_2d
  model_name: v3ae
  n_workers: 0
  # hparams
  batch_size: 500
  learning_rate: 5e-4
  eps: 1e-3
  n_mc_samples: 3
  digits:
    - 2
    - 5
  # ood
  tau_ood: 0.5
  ood_z_generation_method: gd_aggregate_posterior
  prior_b: 0.001
  # misc
  n_trials: 1
  seed: 3
  max_epochs: 200
  # pl trainer
  early_stopping_patience: 200
  log_every_n_steps: 10 # How often to log within steps (defaults to every 50 steps)
  flush_logs_every_n_steps: 10 # How often does the log writes to disc
  progress_bar_refresh_rate: 3 # How often to refresh progress bar (in steps).
  check_val_every_n_epoch: 1 # Check val every n train epochs

- name: b_search_aggregate_posterior_0004
  experiment_name: fashion_mnist_2d
  model_name: v3ae
  n_workers: 0
  # hparams
  batch_size: 500
  learning_rate: 5e-4
  eps: 1e-3
  n_mc_samples: 3
  digits:
    - 2
    - 5
  # ood
  tau_ood: 0.5
  ood_z_generation_method: gd_aggregate_posterior
  prior_b: 0.004
  # misc
  n_trials: 1
  seed: 3
  max_epochs: 200
  # pl trainer
  early_stopping_patience: 200
  log_every_n_steps: 10 # How often to log within steps (defaults to every 50 steps)
  flush_logs_every_n_steps: 10 # How often does the log writes to disc
  progress_bar_refresh_rate: 3 # How often to refresh progress bar (in steps).
  check_val_every_n_epoch: 1 # Check val every n train epochs

- name: b_search_aggregate_posterior_0016
  experiment_name: fashion_mnist_2d
  model_name: v3ae
  n_workers: 0
  # hparams
  batch_size: 500
  learning_rate: 5e-4
  eps: 1e-3
  n_mc_samples: 3
  digits:
    - 2
    - 5
  # ood
  tau_ood: 0.5
  ood_z_generation_method: gd_aggregate_posterior
  prior_b: 0.016
  # misc
  n_trials: 1
  seed: 3
  max_epochs: 200
  # pl trainer
  early_stopping_patience: 200
  log_every_n_steps: 10 # How often to log within steps (defaults to every 50 steps)
  flush_logs_every_n_steps: 10 # How often does the log writes to disc
  progress_bar_refresh_rate: 3 # How often to refresh progress bar (in steps).
  check_val_every_n_epoch: 1 # Check val every n train epochs

- name: b_search_aggregate_posterior_007
  experiment_name: fashion_mnist_2d
  model_name: v3ae
  n_workers: 0
  # hparams
  batch_size: 500
  learning_rate: 5e-4
  eps: 1e-3
  n_mc_samples: 3
  digits:
    - 2
    - 5
  # ood
  tau_ood: 0.5
  ood_z_generation_method: gd_aggregate_posterior
  prior_b: 0.07
  # misc
  n_trials: 1
  seed: 3
  max_epochs: 200
  # pl trainer
  early_stopping_patience: 200
  log_every_n_steps: 10 # How often to log within steps (defaults to every 50 steps)
  flush_logs_every_n_steps: 10 # How often does the log writes to disc
  progress_bar_refresh_rate: 3 # How often to refresh progress bar (in steps).
  check_val_every_n_epoch: 1 # Check val every n train epochs

- name: b_search_aggregate_posterior_025
  experiment_name: fashion_mnist_2d
  model_name: v3ae
  n_workers: 0
  # hparams
  batch_size: 500
  learning_rate: 5e-4
  eps: 1e-3
  n_mc_samples: 3
  digits:
    - 2
    - 5
  # ood
  tau_ood: 0.5
  ood_z_generation_method: gd_aggregate_posterior
  prior_b: 0.25
  # misc
  n_trials: 1
  seed: 3
  max_epochs: 200
  # pl trainer
  early_stopping_patience: 200
  log_every_n_steps: 10 # How often to log within steps (defaults to every 50 steps)
  flush_logs_every_n_steps: 10 # How often does the log writes to disc
  progress_bar_refresh_rate: 3 # How often to refresh progress bar (in steps).
  check_val_every_n_epoch: 1 # Check val every n train epochs
