# %
# Match Nicki and Martin MNIST likelihood
- name: gaussian_vae_match
  experiment_name: mnist
  model_name: vanilla_vae
  n_workers: 0
  # hparams
  batch_size: 512
  learning_rate: 1e-3
  eps: 1e-3
  # From prior_gamma_per_pixel - for MNIST only
  # misc
  n_trials: 3
  seed: 3
  max_epochs: 200
  # pl trainer
  early_stopping_patience: 50
  log_every_n_steps: 50 # How often to log within steps (defaults to every 50 steps)
  flush_logs_every_n_steps: 50 # How often does the log writes to disc
  progress_bar_refresh_rate: 3 # How often to refresh progress bar (in steps).
  check_val_every_n_epoch: 2 # Check val every n train epochs