- name: every_1_epoch
  experiment_name: toy
  # hparams
  batch_size: 500
  hidden_dim: 50
  beta_elbo: 1
  beta_ood: 1
  ood_x_generation_method: optimised_x_ood
  # pl trainer
  n_trials: 10
  max_epochs: 6000
  log_every_n_steps: 500 # How often to log within steps (defaults to every 50 steps)
  flush_logs_every_n_steps: 500 # How often does the log writes to disc
  progress_bar_refresh_rate: 0 # How often to refresh progress bar (in steps).
  # val_check_interval: 5 # How often to check the validation set.
  check_val_every_n_epoch: 1 # Check val every n train epochs

- name: every_10_epoch
  experiment_name: toy
  # hparams
  batch_size: 500
  hidden_dim: 50
  beta_elbo: 1
  beta_ood: 1
  ood_x_generation_method: optimised_x_ood
  # pl trainer
  n_trials: 10
  max_epochs: 6000
  log_every_n_steps: 500 # How often to log within steps (defaults to every 50 steps)
  flush_logs_every_n_steps: 500 # How often does the log writes to disc
  progress_bar_refresh_rate: 0 # How often to refresh progress bar (in steps).
  # val_check_interval: 5 # How often to check the validation set.
  check_val_every_n_epoch: 10 # Check val every n train epochs

- name: every_50_epoch
  experiment_name: toy
  # hparams
  batch_size: 500
  hidden_dim: 50
  beta_elbo: 1
  beta_ood: 1
  ood_x_generation_method: optimised_x_ood
  # pl trainer
  n_trials: 10
  max_epochs: 6000
  log_every_n_steps: 500 # How often to log within steps (defaults to every 50 steps)
  flush_logs_every_n_steps: 500 # How often does the log writes to disc
  progress_bar_refresh_rate: 0 # How often to refresh progress bar (in steps).
  # val_check_interval: 5 # How often to check the validation set.
  check_val_every_n_epoch: 50 # Check val every n train epochs

- name: every_100_epoch
  experiment_name: toy
  # hparams
  batch_size: 500
  hidden_dim: 50
  beta_elbo: 1
  beta_ood: 1
  ood_x_generation_method: optimised_x_ood
  # pl trainer
  n_trials: 10
  max_epochs: 6000
  log_every_n_steps: 500 # How often to log within steps (defaults to every 50 steps)
  flush_logs_every_n_steps: 500 # How often does the log writes to disc
  progress_bar_refresh_rate: 0 # How often to refresh progress bar (in steps).
  # val_check_interval: 5 # How often to check the validation set.
  check_val_every_n_epoch: 100 # Check val every n train epochs

- name: every_500_epoch
  experiment_name: toy
  # hparams
  batch_size: 500
  hidden_dim: 50
  beta_elbo: 1
  beta_ood: 1
  ood_x_generation_method: optimised_x_ood
  # pl trainer
  n_trials: 10
  max_epochs: 6000
  log_every_n_steps: 500 # How often to log within steps (defaults to every 50 steps)
  flush_logs_every_n_steps: 500 # How often does the log writes to disc
  progress_bar_refresh_rate: 0 # How often to refresh progress bar (in steps).
  # val_check_interval: 5 # How often to check the validation set.
  check_val_every_n_epoch: 500 # Check val every n train epochs
